HG\SettingsBundle\Entity\SettingTranslation:
    type: entity
    table: hg_setting_translation
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        locale:
            type: string
        value:
            type: text
            notnull: false
        description:
            type: string
            length: 255
            notnull: false
