<?php

namespace HG\SettingsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingRepository extends EntityRepository
{
 /**
   * visszaadja az összes setting id-ját, ahol a típus 'file'
   * 
   * @return array
   */
  public function getFileTypeSettingsId()
  {
    $fileTypeSettings = $this->createQueryBuilder('s')
    ->where('s.type = :type')
    ->setParameter('type', 'file')
    ->getQuery()
    ->execute();

    $ids = array();

    if (count($fileTypeSettings))
    {
      foreach ($fileTypeSettings as $setting)
      {
        $ids[] = $setting->getId();
      }

      return $ids;
    }
    else
    {
      return $ids;
    }
  }
}
