<?php

namespace Hgabka\SettingsBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * SettingRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function getSettings()
    {
        return $this
            ->createQueryBuilder('s')
            ->getQuery()
            ->getResult(Query::HYDRATE_ARRAY)
        ;
    }

    /**
     * @return array
     */
    public function getVisibleSettings(string $locale)
    {
        return $this
            ->createQueryBuilder('s')
            ->leftJoin('s.translations', 't', 'WITH', 't.locale = :loc')
            ->setParameter('loc', $locale)
            ->orderBy('t.description')
            ->where('s.visible = 1')
            ->getQuery()
            ->getResult()
        ;
    }

    public function getSettingsOrdered(string $locale)
    {
        return
            $this
            ->createQueryBuilder('s')
            ->leftJoin('s.translations', 't', 'WITH', 't.locale = :loc')
            ->setParameter('loc', $locale)
            ->orderBy('t.description')
            ->getQuery()
            ->execute()
        ;
    }
}
