parameters:
    hg_settings.settings_manager.class: 'Hgabka\SettingsBundle\Helper\SettingsManager'

services:
    hg_settings.settings_twig_extension:
        class: Hgabka\SettingsBundle\Twig\HgabkaSettingsTwigExtension
        arguments: ['@hg_settings.settings_manager']
        public: false
        tags:
            - { name: twig.extension }

    hg_settings.setting_subscriber:
        class: Hgabka\SettingsBundle\EventListener\SettingSubscriber
        arguments: ['@hg_settings.settings_manager']
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    hg_settings.admin.settings:
        class: Hgabka\SettingsBundle\Admin\SettingAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: hg_settings.group, icon: '<i class="fa fa-cog"></i>', label: hg_settings.admin.label, label_catalogue: 'HgabkaSettingsBundle', label_translator_strategy: 'sonata.admin.label.strategy.underscore' }
        arguments: [null, Hgabka\SettingsBundle\Entity\Setting, HgabkaSettingsBundle:SettingAdmin]
        calls:
          - [setManager, ["@hg_settings.settings_manager"]]
          - [setDoctrine, ['@doctrine']]

    hg_settings.form.settings:
        class: Hgabka\SettingsBundle\Form\SettingsType
        tags:
            - { name: form.type }
        arguments: ['@hg_settings.settings_manager', '@doctrine', '@event_dispatcher']
        public: true

    hg_settings.settings_manager:
        class: '%hg_settings.settings_manager.class%'
        arguments: ["@doctrine", '@hgabka_utils.hgabka_utils', "%kernel.cache_dir%"]
        public: true

    hg_settings.setting_voter:
        class:  Hgabka\SettingsBundle\Security\SettingVoter
        arguments: ['@security.access.decision_manager', '', '']
        tags:
            - { name: security.voter }
        public: false

    hg_settings.setting_type_string:
        class:  Hgabka\SettingsBundle\Model\StringSettingType
        tags:
            - { name: hg_setting.setting_type }
        public: false

    hg_settings.setting_type_integer:
        class:  Hgabka\SettingsBundle\Model\IntegerSettingType
        tags:
            - { name: hg_setting.setting_type }
        public: false

    hg_settings.setting_type_number:
        class:  Hgabka\SettingsBundle\Model\NumberSettingType
        tags:
            - { name: hg_setting.setting_type }
        public: false

    hg_settings.setting_type_email:
        class:  Hgabka\SettingsBundle\Model\EmailSettingType
        tags:
            - { name: hg_setting.setting_type }
        public: false

    hg_settings.setting_type_bool:
        class:  Hgabka\SettingsBundle\Model\BoolSettingType
        tags:
            - { name: hg_setting.setting_type }
        public: false

    hg_settings.form_type_subscriber:
        class: Hgabka\SettingsBundle\EventListener\GeneralSettingFormTypeSubscriber
        arguments: ['@hg_settings.settings_manager']
        calls:
          - [setAuthChecker, ["@security.authorization_checker"]]
          - [setCreatorRole, ["%hg_settings.creator_role%"]]
        tags:
            - { name: kernel.event_subscriber }

    Hgabka\SettingsBundle\Helper\SettingsManager:
        alias: 'hg_settings.settings_manager'
        public: true

    Hgabka\SettingsBundle\EventListener\BaseSettingFormTypeSubscriber:
        alias: 'hg_settings.form_type_subscriber'
        public: true
