parameters:
    hg_settings.settings_manager.class: 'Hgabka\SettingsBundle\Helper\SettingsManager'

services:
    hg_settings.settings_twig_extension:
        class: Hgabka\SettingsBundle\Twig\HgabkaSettingsTwigExtension
        arguments: ['@hg_settings.settings_manager']
        public: false
        tags:
            - { name: twig.extension }

    hg_settings.setting_subscriber:
        class: Hgabka\SettingsBundle\EventListener\SettingSubscriber
        arguments: ['@hg_settings.settings_manager']
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    hg_settings.admin.settings:
        class: Hgabka\SettingsBundle\Admin\SettingAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: hg_settings, label: hg_settings.admin.label, label_catalogue: 'HgabkaSettingsBundle' }
        arguments: [null, Hgabka\SettingsBundle\Entity\Setting, HgabkaSettingsBundle:SettingAdmin]
        calls:
          - [setManager, ["@hg_settings.settings_manager"]]

    hg_settings.form.settings:
        class: Hgabka\SettingsBundle\Form\SettingsType
        tags:
            - { name: form.type }
        arguments: ['@hg_settings.settings_manager', '@doctrine']

    hg_settings.settings_manager:
        class: '%hg_settings.settings_manager.class%'
        arguments: ["@doctrine", "%kernel.cache_dir%"]
        public: true

    hg_settings.setting_voter:
        class:  Hgabka\SettingsBundle\Security\SettingVoter
        arguments: ['@security.access.decision_manager', '', '']
        tags:
            - { name: security.voter }
        public: false

    Hgabka\SettingsBundle\Helper\SettingsManager: '@hg_settings.settings_manager'