parameters:
    hg_settings.settings_manager.class: 'Hgabka\SettingsBundle\Helper\SettingsManager'

services:
    hg_settings.settings_twig_extension:
        class: Hgabka\SettingsBundle\Twig\HgabkaSettingsTwigExtension
        arguments: ['@hg_settings.settings_manager']
        public: false
        tags:
            - { name: twig.extension }

    hg_settings.setting_subscriber:
        class: Hgabka\SettingsBundle\EventListener\SettingSubscriber
        arguments: ['@hg_settings.settings_manager']
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    hg_settings.admin.settings:
        class: Hgabka\SettingsBundle\Admin\SettingAdmin
        tags:
            - { name: sonata.admin, model_class: Hgabka\SettingsBundle\Entity\Setting, controller: Hgabka\SettingsBundle\Controller\SettingAdminController, manager_type: orm, group: hg_settings.group, icon: '<i class="fa fa-cog"></i>', label: hg_settings.admin.label, label_translator_strategy: 'sonata.admin.label.strategy.underscore', on_top: true, translation_domain: 'messages' }
        calls:
          - [setManager, ["@hg_settings.settings_manager"]]
          - [setDoctrine, ['@doctrine']]
          - [setSecurity, [ '@security.helper' ]]
          - [setCreatorRole, ['%hg_settings.creator_role%']]
          - [setEditorRole, ['%hg_settings.editor_role%']]

    hg_settings.admin.redirect:
        class: Hgabka\SettingsBundle\Admin\RedirectAdmin
        tags:
            - { name: sonata.admin, model_class: Hgabka\SettingsBundle\Entity\Redirect, controller: ~, manager_type: orm, group: hg_settings.redirect_group, icon: '<i class="fa fa-rotate-right"></i>', label: hg_settings.admin.redirect, label_translator_strategy: 'sonata.admin.label.strategy.underscore', translation_domain: 'messages' }

    hg_settings.form.settings:
        class: Hgabka\SettingsBundle\Form\SettingsType
        tags:
            - { name: form.type }
        arguments: ['@hg_settings.settings_manager', '@doctrine', '@event_dispatcher','@hgabka_utils.hgabka_utils']
        public: true

    hg_settings.settings_manager:
        class: '%hg_settings.settings_manager.class%'
        arguments: ["@doctrine", '@hgabka_utils.hgabka_utils', "%kernel.cache_dir%"]
        public: true

    hg_settings.setting_voter:
        class:  Hgabka\SettingsBundle\Security\SettingVoter
        arguments: ['@security.access.decision_manager', '', '']
        tags:
            - { name: security.voter }
        public: false

    hg_settings.setting_type_string:
        class:  Hgabka\SettingsBundle\Model\StringSettingType
        tags:
            - { name: hg_setting.setting_type }
        public: false

    hg_settings.setting_type_integer:
        class:  Hgabka\SettingsBundle\Model\IntegerSettingType
        tags:
            - { name: hg_setting.setting_type }
        public: false

    hg_settings.setting_type_number:
        class:  Hgabka\SettingsBundle\Model\NumberSettingType
        tags:
            - { name: hg_setting.setting_type }
        public: false

    hg_settings.setting_type_email:
        class:  Hgabka\SettingsBundle\Model\EmailSettingType
        tags:
            - { name: hg_setting.setting_type }
        public: false

    hg_settings.setting_type_bool:
        class:  Hgabka\SettingsBundle\Model\BoolSettingType
        tags:
            - { name: hg_setting.setting_type }
        public: false

    hg_settings.setting_type_text:
        class:  Hgabka\SettingsBundle\Model\TextSettingType
        tags:
            - { name: hg_setting.setting_type }
        public: false

    hg_settings.setting_type_wysiwyg:
        class:  Hgabka\SettingsBundle\Model\WysiwygSettingType
        tags:
            - { name: hg_setting.setting_type }
        public: false

    hg_settings.setting_type_datetimerange:
        class:  Hgabka\SettingsBundle\Model\DatetimeRangeSettingType
        tags:
            - { name: hg_setting.setting_type }
        public: false

    hg_settings.form_type_subscriber:
        class: Hgabka\SettingsBundle\EventListener\GeneralSettingFormTypeSubscriber
        arguments: ['@hg_settings.settings_manager']
        calls:
          - [setAuthChecker, ["@security.authorization_checker"]]
          - [setCreatorRole, ["%hg_settings.creator_role%"]]
        tags:
            - { name: kernel.event_subscriber }

    Hgabka\SettingsBundle\Helper\SettingsManager:
        alias: 'hg_settings.settings_manager'
        public: true

    Hgabka\SettingsBundle\EventListener\BaseSettingFormTypeSubscriber:
        alias: 'hg_settings.form_type_subscriber'
        public: true
        
    Hgabka\SettingsBundle\Controller\SettingAdminController:
        autowire: true
        autoconfigure: true        

    hg_settings.repositories.redirect:
        class:            Hgabka\SettingsBundle\Repository\RedirectRepository
        factory:          ['@doctrine.orm.entity_manager', getRepository]
        arguments:        [Hgabka\SettingsBundle\Entity\Redirect]

    hg_settings.redirectrouter:
        class: Hgabka\SettingsBundle\Router\RedirectRouter
        arguments: ['@hg_settings.repositories.redirect']
        tags:
            - { name: router, priority: 1 }
